training:
  base_lr_low: 1e-3
  base_lr_high: 1e-1
  lr_factor: 0.1
  weight_decay_low: 1e-5
  weight_decay_high: 1e-3
  rank_weight: 1.0
  momentum_low: 0.85
  momentum_high: 0.99
  batch_size: 16
  learning_rate: 0.001
  epochs_low: 100
  epochs_high: 200

  print_freq: 287
  validate_freq: 1
  classnumber: 2
  input_size: 224
  data_path: '../data/processed/IDID_cropped_224'
  save_path: '../models/coral_25_06_v2' #orca_14_06_v2' #acc_baseline' #hailo_resnet_again_foreign_v4' #_zeroes'
  model_name: 'mobilenet'

  port: 5000
  device: 'cuda'
  gpu: '0'
  ntrials: 50
  njobs: 1
  bslnid: 0
  orca_dev_ip: '192.168.2.37' #'192.168.1.15' #192.168.1.15 # fix
  orca_port: 5003
  #ds_device_ip: '192.168.188.202'
  ds_device_ip_hailo: 'compiler_api'
  ds_device_ip_orca: 'compiler_api' #'0.0.0.0' #'192.168.188.202'
  ds_device_ip_coral: 'compiler_api' #'0.0.0.0' #'192.168.188.202'
  ds_device_ip_st: 'compiler_api' #192.168.2.97 #'192.168.188.202'
  study_name: 'coral_25_06_v2' #orca_14_06_v2' #'coral_optim_mbln_wed' #'hailo_resnet_again_foreign_v4' #'hailo_mobilenet_zeroes_v3' #'haio_only_optimization_22_05_2025_v7'
  st_dev_ip: '192.168.2.37'
  st_port: 5003
  hailo_port: 5000
  target_dev: 'coral'
secrets:
  database_name:  ${oc.env:DTBS_NAME, 'optuna_db'}
  port:  ${oc.env:PORT, '5432'}
  network:  ${oc.env:NTWRK, 'optuna-postgres'}
  pswrd:  ${oc.env:PSSWRD, 'secretpass'}
  usrnm:  ${oc.env:OPTUNA_USRNM, 'optuna_user'}
