classifier:
  modelname: 'temporal_optimization_model'
  model_zoo_dir: "../../../models/"
  train_set_dir: '../../../data/processed/IDID_cropped_224/train/'
  val_set_dir: '../../../data/processed/IDID_cropped_224/val/'
  test_set_dir: '../../../data/processed/IDID_cropped_224/test/'
