general:
   model_path: 
operation_mode: quantization

dataset:
   training_path: /home/alema416/dev/work/HI4Lines_Insp/data/processed/IDID_cropped_224/train
   validation_path: /home/alema416/dev/work/HI4Lines_Insp/data/processed/IDID_cropped_224/val
   test_path: /home/alema416/dev/work/HI4Lines_Insp/data/processed/IDID_cropped_224/test
   quantization_path: /home/alema416/dev/work/HI4Lines_Insp/data/processed/IDID_cropped_224/train
   quantization_split: 0.05

preprocessing:
   rescaling:
      scale:  [0.0213538, 0.0208032, 0.0197237]
      offset: [-2.7478418, -2.4465773, -2.1585231]
   resizing:
      aspect_ratio: fit
      interpolation: bilinear
   color_mode: rgb
   
quantization:
   quantizer: Onnx_quantizer
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float
   granularity: per_channel
   extra_options: calib_moving_average
mlflow:
   uri: ./experiments_outputs/mlruns

hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}

